# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: api-gateway-config
#   namespace: patient-service
# data:
#   application-prod.yml: |
#     server:
#       port: 4004

#     auth:
#       service:
#         url: http://auth-service.patient-service.svc.cluster.local:4005

#     spring:
#       cloud:
#         gateway:
#           routes:
#             - id: auth-service-route
#               uri: http://auth-service.patient-service.svc.cluster.local:4005
#               predicates:
#                 - Path=/auth/**
#               filters:
#                 - StripPrefix=1

#             - id: patient-service-route
#               uri: http://patient-service.patient-service.svc.cluster.local:4000
#               predicates:
#                 - Path=/api/patients/**
#               filters:
#                 - StripPrefix=1
#                 - name: JwtValidation

#     jwt:
#       secret: "7tBuVpfD0dGM6xtQJi3Ft+1X2WYyolM97aP3LEpHSx0=" 

apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: patient-service
data:
  application-prod.yml: |
    server:
      port: 4004

    auth:
      service:
        url: http://auth-service.patient-service.svc.cluster.local:4005

    spring:
      cloud:
        gateway:
          routes:
            - id: auth-service-route
              uri: http://auth-service.patient-service.svc.cluster.local:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: patient-service-route
              uri: http://patient-service.patient-service.svc.cluster.local:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1
                - name: JwtValidation

    jwt:
      secret: "7tBuVpfD0dGM6xtQJi3Ft+1X2WYyolM97aP3LEpHSx0="
  # Individual keys for environment variables
  auth.service.url: "http://auth-service.patient-service.svc.cluster.local:4005"
  jwt.secret: "7tBuVpfD0dGM6xtQJi3Ft+1X2WYyolM97aP3LEpHSx0="