apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-gateway-secrets
  namespace: patient-service
spec:
  provider: aws
  parameters:
    region: us-east-2
    objects: |
      - objectName: "api-gateway/jwt-secret"
        objectType: secretsmanager
        jmesPath:
          - path: jwt_secret
            objectAlias: JWT_SECRET
  secretObjects:
    - secretName: api-gateway-secrets
      type: Opaque
      data:
        - objectName: JWT_SECRET
          key: jwt.secret