---
apiVersion: v1
kind: ConfigMap
metadata:
  name: patient-service-config
  namespace: patient-service
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: "org.apache.kafka.common.serialization.ByteArraySerializer"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.apache.kafka.common.serialization.ByteArrayDeserializer"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_SQL_INIT_MODE: "always"
  BILLING_SERVICE_ADDRESS: "billing-service.patient-service.svc.cluster.local"
  BILLING_SERVICE_GRPC_PORT: "9005"
  JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
  SERVER_PORT: "4000"

---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: patient-service
  labels:
    app: patient-service
spec:
  type: ClusterIP
  selector:
    app: patient-service
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  - name: debug
    port: 5005
    targetPort: 5005
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: patient-service-hpa
  namespace: patient-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: patient-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70