apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: patient-service
  labels:
    app: patient-service
spec:
  type: ClusterIP
  selector:
    app: patient-service
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  - name: debug
    port: 5005
    targetPort: 5005
