apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: patient-service-secrets
  namespace: patient-service
spec:
  provider: aws
  parameters:
    region: us-east-2
    objects: |
      - objectName: "patient-service/db-credentials"
        objectType: secretsmanager
        jmesPath:
          - path: username
            objectAlias: DB_USERNAME
          - path: password
            objectAlias: DB_PASSWORD
          - path: database
            objectAlias: DB_NAME
  secretObjects:
    - secretName: patient-service-secrets
      type: Opaque
      data:
        - objectName: DB_USERNAME
          key: DB_USERNAME
        - objectName: DB_PASSWORD
          key: DB_PASSWORD
        - objectName: DB_NAME
          key: DB_NAME