apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: 361509912577.dkr.ecr.us-east-2.amazonaws.com/micro-services/billing-service:02d1676e6cc09f638917df7dacac63c881a0be43
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
            - containerPort: 9001
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
