apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: patient-service
spec:
  serviceAccountName: patient-service-sa
  containers:
  - name: debug
    image: amazonlinux
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
  restartPolicy: Never