spring.application.name=auth-service
server.port=4005

# Database initialization
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update

# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.enabled-by-default=true

# Logging levels
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.com.pm.authservice=DEBUG