apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: 361509912577.dkr.ecr.us-east-2.amazonaws.com/micro-services/billing-service:V0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
            - containerPort: 9001
          resources:
            requests:
              cpu: "150m"
              memory: "192Mi"
            limits:
              cpu: "300m"
              memory: "400Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: patient-service
spec:
  type: ClusterIP
  selector:
    app: billing-service
  ports:
    - name: http
      port: 4001
      targetPort: 4001
    - name: grpc
      port: 9001
      targetPort: 9001