name: Deploy dev edfx AWS Account

on:
  workflow_dispatch:
    inputs:
      Action:
        description: "Select Terraform Action"
        required: true
        type: choice
        options:
          - apply
          - destroy
        default: apply

permissions:
  contents: read
  issues: write

jobs:
  plan-and-apply-dev:
    permissions:
      id-token: write
      contents: read
      issues: write
    uses: ./.github/workflows/infra-deploy.yml
    with:
      environment: edfx-dev
      WORKING_DIR: Aws-infra/iac/
      Terraform_Backend_Configuration_File: tf_env/Backend_Edfx_Config_Ohio.config
      Terraform_Deployment_Configuration_File: tf_env/Dev_Edfx_Deployment.tfvars
      Action: ${{ github.event.inputs.Action }}
    secrets: inherit
